apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.names.fullname" . }}-license.conf
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: firstspirit
data:
  fs-license.conf: {{ required "License file must be provided" .Values.firstspirit.license | b64enc }}